### ISSUE TITLE
Implement named State-maps

### ISSUE THREAD

**Issue by corneil** [open-jumpco/kfsm#1]
Should we support named state-maps?
How would the be defined?
Initial views:
One set of events for the state machine as a whole.
Each state map operates on a context using a specific interface. A state machine instance has one context and it implements all said interfaces. 
A map has a set of possible states that could be defined explicitly by providing a set or implicitly by providing an enum or sealed class.
```kotlin
stateMachine(States::class, Events::class, GlobalContext::class) {
  stateMap(setOf(States.S1,States.S2,States.S3), Events::class, ContextInterface::class) {
    state(States.S1) {
      on(Events.E1 to States.S2) {
      }
      push(Events.E2, "separate", States.S4) {
      }
  }
  stateMap("separate", setOf(States.S4, States.S1), Events::class, SeparateContext::class) {
      state(States.S4) {
        on(Events.E2 to States.S1) {
          someAction()
        }
      }
      state(States.S1) {
        pop(Events.E1, States.S3, guard = { value == 42 }) {
          specialClosing()
        }
        pop(Events.E1) {
          closing()
        }
      }
  }
}
```

**Comment by jvalkeal** [comment]
I think I'm a perfect example of a super duper naive user what comes for a kotlin and everything you're trying to accomplish here. As dsl should be relatively self explanatory I have to ask what what a `push` and `pop` would mean in a statemachine world.

**Comment by corneil** [comment]
Push would place current state on a stack and enter new state in a different state map. This will allow hierarchical state machines. In the sub state map you can pop which will transition back to map you pushed. And when you pop you can provide a new target. The relevant state entry and exit actions will be invoked.
In cases where things get complex you will be able to compose a state machine from different maps. Pushing and popping allows for managing this sub state without the knowing how it was entered.

**Comment by corneil** [comment]
They could be written as:
`onEventPush` if that makes more sense.

**Comment by corneil** [comment]
Another way to extend the DSL may be:
````kotlin
stateMachine(States::class, Events::class, GlobalContext::class) {
  stateMap(setOf(States.S1,States.S2,States.S3), Events::class, ContextInterface::class) {
    state(States.S1) {
      on(Events.E1) {
        transition(States.S2) {
        }
      }
      on(Events.E2) {
        push("separate", States.S4) {
        }
      }
    }
  }
  stateMap("separate", setOf(States.S4, States.S1), Events::class, SeparateContext::class) {
      state(States.S4) {
        on(Events.E2) {
          transition(States.S1) {
            someAction()
          }
        }
      }
      state(States.S1) {
        on(Events.E1) {
          pop(States.S3, guard = { value == 42 }) {
            specialClosing()
          }
        }
        on(Events.E1) {
            pop {
              closing()
           }
        }
      }
  }
}
````

**Comment by corneil** [comment]
My feeling is that having variations of `on` for different transitions may be more readable than extra nested element.
```kotlin
{
  on(Events.E1 to States.S1) {}
  onEventPush(Events.E1, "map2", States.S2){}
  onEventPop(Events.E2){}
  onEventPop(Events.E2, States.S3) {}
  onEventPop(Events.E2, "map3", States.S4) {}
}
```
Shorter
```kotlin
{
  on(Events.E1 to States.S1) {}
  pushOn(Events.E1, "map2", States.S2){}
  popOn(Events.E2){}
  popOn(Events.E2, States.S3) {}
  popOn(Events.E2, "map3", States.S4) {}
}
```

**Comment by jvalkeal** [comment]
Right ok, maybe using a keyword `transition` would then better describe that state is going to get changed.

**Comment by corneil** [comment]
If `transition` comes off much better than `on` to someone deeply invested in state machines I think it is a good idea to make the change.

**Comment by corneil** [comment]
Implemented
