### ISSUE TITLE
Define dependency for `common` target

### ISSUE THREAD

**Issue by beretis** [open-jumpco/kfsm#14]
I would like to use this library in common code, from what I saw in `build.gradle`, pretty much all platforms are supported. Would it be possible to introduce mavenPublication for `common` target? 
Thank you

**Comment by corneil** [comment]
Let me check what went wrong

**Comment by corneil** [comment]
The kfsm dependency you find here [https://repo1.maven.org/maven2/io/jumpco/open/kfsm/1.6.0/](https://repo1.maven.org/maven2/io/jumpco/open/kfsm/1.6.0/) is the common one. kfsm-jvm is the java specific one.
So you common code should depend on `io.jumpco.open:kfsm:1.6.0`
